# Generated by Django 4.2.4 on 2023-08-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'permissions': [('pode_reservar_pelo_site', 'Permissão que autoriza o hospede a fazer a reserva pelo site.')]},
        ),
    ]
